# Python Array NumPy Concatination and Spliting.

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,17).reshape(4,4)

In [3]:
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
arr2=np.arange(17,33).reshape(4,4)

In [5]:
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [6]:
list1=[1,2,3,4]

In [7]:
list2=[5,6,7,8]

In [8]:
list1+list2 # Concatination of a list.

[1, 2, 3, 4, 5, 6, 7, 8]

In [9]:
np.concatenate((arr1,arr2)) # Column wise Concatination.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [10]:
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [11]:
np.concatenate((arr1,arr2),axis = 1) # Row wise Concatination

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [12]:
np.vstack((arr1,arr2)) # Vertical Concatination .

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [13]:
np.hstack((arr1,arr2)) # Horizontal Concatenation

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [21]:
arr3=np.arange(3,34,2).reshape(4,4)

In [22]:
print(arr3)

[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]
 [27 29 31 33]]


In [23]:
np.vstack((arr1,arr2,arr3))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25],
       [27, 29, 31, 33]])

In [24]:
np.hstack((arr1,arr2,arr3))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  3,  5,  7,  9],
       [ 5,  6,  7,  8, 21, 22, 23, 24, 11, 13, 15, 17],
       [ 9, 10, 11, 12, 25, 26, 27, 28, 19, 21, 23, 25],
       [13, 14, 15, 16, 29, 30, 31, 32, 27, 29, 31, 33]])

# Split

In [25]:
np.split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [26]:
np.split(arr2,4)

[array([[17, 18, 19, 20]]),
 array([[21, 22, 23, 24]]),
 array([[25, 26, 27, 28]]),
 array([[29, 30, 31, 32]])]

In [32]:
np.split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [33]:
list10=np.split(arr1,2)

In [34]:
type(list10)

list

In [35]:
list10[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
list10[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
type(list10[0])

numpy.ndarray

In [39]:
np.split(arr1,2,axis=0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [40]:
np.split(arr1,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [41]:
np.split(arr1,4,axis=1)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [42]:
d1=np.array([4,5,6,7,8,9])

In [43]:
np.split(d1,[1,3])

[array([4]), array([5, 6]), array([7, 8, 9])]