# Random Sampling with Numpy

In [1]:
import numpy as np
import random


In [3]:
np.random.random(1)# Generates one random value

array([0.85143007])

In [4]:
np.random.random((3,3)) # Generates 3X3 random value

array([[0.35439484, 0.38953538, 0.28055673],
       [0.53035468, 0.55579871, 0.72293691],
       [0.52711611, 0.33465594, 0.44460149]])

In [9]:
np.random.randint(1,4) # Generates Random value with integer between specified range.

2

In [10]:
np.random.randint(1,4,(4,4))

array([[2, 2, 3, 1],
       [3, 2, 1, 3],
       [1, 3, 3, 2],
       [2, 1, 2, 2]])

In [12]:
np.random.randint(1,4,(2,3,3))

array([[[3, 2, 3],
        [3, 3, 2],
        [3, 2, 1]],

       [[1, 3, 3],
        [2, 1, 1],
        [1, 3, 2]]])

In [13]:
np.random.seed(10) #It helps to remember the random generated value.
np.random.randint(1,5,(3,4,4))

array([[[2, 2, 1, 4],
        [1, 2, 4, 1],
        [2, 2, 1, 2],
        [2, 3, 1, 2]],

       [[1, 3, 1, 3],
        [1, 4, 1, 1],
        [4, 4, 3, 1],
        [4, 3, 3, 2]],

       [[1, 1, 3, 2],
        [4, 3, 2, 2],
        [2, 4, 2, 3],
        [2, 1, 3, 3]]])

In [16]:
np.random.rand(11)

array([0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715,
       0.54758616, 0.819287  , 0.19894754, 0.8568503 , 0.35165264,
       0.75464769])

In [17]:
np.random.rand(3,4) # Generates Random value between (0,1)

array([[0.29596171, 0.88393648, 0.32551164, 0.1650159 ],
       [0.39252924, 0.09346037, 0.82110566, 0.15115202],
       [0.38411445, 0.94426071, 0.98762547, 0.45630455]])

In [18]:
np.random.randn(3,3)# Gives random positive and negative value.(between -1,1)

array([[-0.53987907,  0.70816002,  0.84222474],
       [ 0.2035808 ,  2.39470366,  0.91745894],
       [-0.11227247, -0.36218045, -0.23218226]])

In [19]:
x=[1,5,7,9]
np.random.choice(x)# Choice function generates the random value from x-list 


7

In [21]:
for i in range(20):
    print(np.random.choice(x))

1
7
9
9
9
5
7
5
5
7
1
7
5
1
5
5
1
5
7
1


In [22]:
x

[1, 5, 7, 9]

In [23]:
np.random.permutation(x)

array([1, 5, 9, 7])

In [24]:
for i in range(20):
    print(np.random.permutation(x))

[9 7 1 5]
[9 7 5 1]
[5 7 9 1]
[5 1 9 7]
[9 5 7 1]
[5 1 9 7]
[9 1 5 7]
[7 5 1 9]
[1 7 9 5]
[1 9 7 5]
[1 7 5 9]
[5 7 1 9]
[7 1 9 5]
[1 9 7 5]
[7 9 5 1]
[7 9 5 1]
[1 7 5 9]
[1 9 5 7]
[1 9 5 7]
[7 9 1 5]
