In [1]:
import numpy as np

In [2]:
arr_1= np.arange(1,10).reshape(3,3)

In [3]:
print(arr_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr_2=np.arange(3,21,2).reshape(3,3)

In [5]:
print(arr_2)

[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]]


# Add

In [10]:
arr_1+arr_2

array([[ 4,  7, 10],
       [13, 16, 19],
       [22, 25, 28]])

In [6]:
np.add(arr_1,arr_2)

array([[ 4,  7, 10],
       [13, 16, 19],
       [22, 25, 28]])

# Subtract

In [11]:
arr_1-arr_2

array([[ -2,  -3,  -4],
       [ -5,  -6,  -7],
       [ -8,  -9, -10]])

In [15]:
np.subtract(arr_1,arr_2)

array([[ -2,  -3,  -4],
       [ -5,  -6,  -7],
       [ -8,  -9, -10]])

# Multiply

In [16]:
arr_1*arr_2

array([[  3,  10,  21],
       [ 36,  55,  78],
       [105, 136, 171]])

In [8]:
np.multiply(arr_1,arr_2)

array([[  3,  10,  21],
       [ 36,  55,  78],
       [105, 136, 171]])

# Divide

In [17]:
arr_1/arr_2

array([[0.33333333, 0.4       , 0.42857143],
       [0.44444444, 0.45454545, 0.46153846],
       [0.46666667, 0.47058824, 0.47368421]])

In [18]:
np.divide(arr_1,arr_2)

array([[0.33333333, 0.4       , 0.42857143],
       [0.44444444, 0.45454545, 0.46153846],
       [0.46666667, 0.47058824, 0.47368421]])

# Matrix Multiplication

In [19]:
arr_1@arr_2

array([[ 66,  78,  90],
       [147, 177, 207],
       [228, 276, 324]])

In [20]:
arr_1.dot(arr_2)

array([[ 66,  78,  90],
       [147, 177, 207],
       [228, 276, 324]])

# finding maximum value in an array using max() function.

In [21]:
arr_1.max()

9

In [22]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr_2.max()


19

In [24]:
arr_2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

# finding minimum value in an array using min() function

In [32]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr_1.min()

1

In [34]:
arr_2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [35]:
arr_2.min()

3

# function to finding the index of maximum value.

In [25]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr_1.argmax()

8

In [27]:
arr_2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [28]:
arr_2.argmax()

8

# function to finding the index of minimum value.

In [36]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr_1.argmin()

0

In [38]:
arr_2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [39]:
arr_2.argmin()

0

# finding maxium value in each column or each row of a given matrix.

In [29]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr_1.max(axis = 0) # where zero represent column and 1 represent row.

array([7, 8, 9])

In [31]:
arr_1.max(axis = 1) # where zero represent column and 1 represent row.

array([3, 6, 9])

# finding maxium value in each column or each row of a given matrix.


In [40]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr_1.min(axis=0) # where zero represent column and 1 represent row.

array([1, 2, 3])

In [42]:
arr_1.min(axis = 1) # where zero represent column and 1 represent row.

array([1, 4, 7])

# finding Sum of all element of an array.

In [43]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr_1.sum() #a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)

45

In [45]:
arr_2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [46]:
arr_2.sum() #a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)

99

# finding the sum of column or row of an array

In [50]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr_1.sum(axis=1) # sum of all row 

array([ 6, 15, 24])

In [51]:
arr_1.sum(axis=0) # sum of all column.

array([12, 15, 18])

# finding mean/avg of all element of a Matrix


In [52]:
np.mean(arr_1)


5.0

In [53]:
arr_1.mean()

5.0

In [56]:
avg=arr_1.sum()/9

In [57]:
print(avg)

5.0


# Finding Square Root Of All Element of a matrix.

In [58]:
np.sqrt(arr_1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

# Finding Standard Division Of a Matrix.

In [60]:
np.std(arr_1)

2.581988897471611

In [61]:
np.std(arr_2)

5.163977794943222

# Finding Exponent of all element of a Matrix.

In [62]:
np.exp(arr_1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [63]:
np.exp(arr_2)

array([[2.00855369e+01, 1.48413159e+02, 1.09663316e+03],
       [8.10308393e+03, 5.98741417e+04, 4.42413392e+05],
       [3.26901737e+06, 2.41549528e+07, 1.78482301e+08]])

# Finding Log of all element of a Matrix.

In [64]:
np.log(arr_1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [65]:
np.log(arr_2)

array([[1.09861229, 1.60943791, 1.94591015],
       [2.19722458, 2.39789527, 2.56494936],
       [2.7080502 , 2.83321334, 2.94443898]])

In [66]:
np.log10(arr_1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [67]:
np.log10(arr_2)

array([[0.47712125, 0.69897   , 0.84509804],
       [0.95424251, 1.04139269, 1.11394335],
       [1.17609126, 1.23044892, 1.2787536 ]])