# Numpy Function:


In [1]:
import numpy as np

# arange()

In [2]:
#np.arange(start, End , steps)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [3]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

# linespace()

In [4]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [5]:
arr_1d= np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [6]:
print(arr_1d)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
arr_1d.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
arr_1d.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [9]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [11]:
arrMult=np.arange(1,13).reshape(2,3,2)

In [12]:
print(arrMult)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ravel()


In [13]:
arrMult.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

arrMult.ravel()

# flatten()

In [14]:
arrMult.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [15]:
arr_2d_Matrix=np.arange(1,13).reshape(3,4)

In [16]:
print(arr_2d_Matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
arr_2d_Matrix.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [18]:
arr_2d_Matrix.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])