# import numpy as np


In [2]:
m_ones=np.ones((2))

In [3]:
m_ones.dtype

dtype('float64')

In [4]:
m_1s=np.ones((5,5))

In [5]:
m_1s.dtype


dtype('float64')

In [6]:
m_1s.shape

(5, 5)

In [7]:
m_1s.size

25

In [8]:
print(m_1s)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
mx_1s=np.ones((3,4),dtype=int)

In [10]:
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [11]:
mx_0s=np.zeros((5,5))

In [12]:
print(mx_0s)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
mx_0s=np.zeros((5,5),dtype=bool)

In [14]:
print(mx_0s)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [15]:
mx_0s=np.zeros((5,5),dtype=str)

In [16]:
print(mx_0s)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]
